// Mock Data for Print-Xpress Demo

import { PrintJob } from '../types';

// Mock Recent Print Jobs (≥20 items for demo)
export const mockRecentJobs: PrintJob[] = [
  {
    id: 'job1',
    userId: 'user1',
    fileName: 'Contract_Final_Signed.pdf',
    fileSize: 1.2,
    fileUrl: 'mock://file1.pdf',
    fileType: 'pdf',
    colorMode: 'bw',
    paperSize: 'a4',
    copies: 1,
    totalPages: 4,
    highQuality: false,
    totalCost: 0.40,
    status: 'completed',
    atmId: 'atm1',
    atmName: 'Downtown Station (A2)',
    createdAt: new Date(Date.now() - 86400000), // Yesterday
    updatedAt: new Date(Date.now() - 86400000),
    completedAt: new Date(Date.now() - 86400000),
  },
  {
    id: 'job2',
    userId: 'user1',
    fileName: 'Exam_Review_Notes.docx',
    fileSize: 3.6,
    fileUrl: 'mock://file2.docx',
    fileType: 'docx',
    colorMode: 'bw',
    paperSize: 'a4',
    copies: 1,
    totalPages: 12,
    highQuality: false,
    totalCost: 1.20,
    status: 'completed',
    atmId: 'atm1',
    atmName: 'Downtown Station (A2)',
    createdAt: new Date(Date.now() - 2 * 86400000),
    updatedAt: new Date(Date.now() - 2 * 86400000),
    completedAt: new Date(Date.now() - 2 * 86400000),
  },
  {
    id: 'job3',
    userId: 'user1',
    fileName: 'Resume_2024.pdf',
    fileSize: 0.8,
    fileUrl: 'mock://file3.pdf',
    fileType: 'pdf',
    colorMode: 'color',
    paperSize: 'a4',
    copies: 3,
    totalPages: 2,
    highQuality: true,
    totalCost: 2.25,
    status: 'completed',
    atmId: 'atm2',
    atmName: 'Campus Center (B1)',
    createdAt: new Date(Date.now() - 3 * 86400000),
    updatedAt: new Date(Date.now() - 3 * 86400000),
    completedAt: new Date(Date.now() - 3 * 86400000),
  },
  {
    id: 'job4',
    userId: 'user1',
    fileName: 'Flight_Tickets.pdf',
    fileSize: 0.5,
    fileUrl: 'mock://file4.pdf',
    fileType: 'pdf',
    colorMode: 'bw',
    paperSize: 'a4',
    copies: 2,
    totalPages: 1,
    highQuality: false,
    totalCost: 0.20,
    status: 'completed',
    atmId: 'atm1',
    atmName: 'Downtown Station (A2)',
    createdAt: new Date(Date.now() - 5 * 86400000),
    updatedAt: new Date(Date.now() - 5 * 86400000),
    completedAt: new Date(Date.now() - 5 * 86400000),
  },
  {
    id: 'job5',
    userId: 'user1',
    fileName: 'Project_Proposal_Draft.docx',
    fileSize: 4.2,
    fileUrl: 'mock://file5.docx',
    fileType: 'docx',
    colorMode: 'color',
    paperSize: 'a4',
    copies: 1,
    totalPages: 15,
    highQuality: true,
    totalCost: 5.63,
    status: 'completed',
    atmId: 'atm3',
    atmName: 'Mall Plaza (C3)',
    createdAt: new Date(Date.now() - 7 * 86400000),
    updatedAt: new Date(Date.now() - 7 * 86400000),
    completedAt: new Date(Date.now() - 7 * 86400000),
  },
  {
    id: 'job6',
    userId: 'user1',
    fileName: 'Invoice_Q4_2023.pdf',
    fileSize: 1.1,
    fileUrl: 'mock://file6.pdf',
    fileType: 'pdf',
    colorMode: 'bw',
    paperSize: 'a4',
    copies: 1,
    totalPages: 3,
    highQuality: false,
    totalCost: 0.30,
    status: 'completed',
    atmId: 'atm1',
    atmName: 'Downtown Station (A2)',
    createdAt: new Date(Date.now() - 10 * 86400000),
    updatedAt: new Date(Date.now() - 10 * 86400000),
    completedAt: new Date(Date.now() - 10 * 86400000),
  },
  {
    id: 'job7',
    userId: 'user1',
    fileName: 'Meeting_Agenda.docx',
    fileSize: 0.6,
    fileUrl: 'mock://file7.docx',
    fileType: 'docx',
    colorMode: 'bw',
    paperSize: 'a4',
    copies: 5,
    totalPages: 2,
    highQuality: false,
    totalCost: 1.00,
    status: 'completed',
    atmId: 'atm2',
    atmName: 'Campus Center (B1)',
    createdAt: new Date(Date.now() - 12 * 86400000),
    updatedAt: new Date(Date.now() - 12 * 86400000),
    completedAt: new Date(Date.now() - 12 * 86400000),
  },
  {
    id: 'job8',
    userId: 'user1',
    fileName: 'Presentation_Slides.pdf',
    fileSize: 8.5,
    fileUrl: 'mock://file8.pdf',
    fileType: 'pdf',
    colorMode: 'color',
    paperSize: 'a4',
    copies: 1,
    totalPages: 24,
    highQuality: true,
    totalCost: 9.00,
    status: 'completed',
    atmId: 'atm1',
    atmName: 'Downtown Station (A2)',
    createdAt: new Date(Date.now() - 14 * 86400000),
    updatedAt: new Date(Date.now() - 14 * 86400000),
    completedAt: new Date(Date.now() - 14 * 86400000),
  },
];

// Generate OTP (6 digits)
export const generateOTP = (): string => {
  return Math.floor(100000 + Math.random() * 900000).toString();
};

// Calculate print cost
export const calculatePrintCost = (
  pages: number,
  colorMode: 'bw' | 'color',
  copies: number,
  highQuality: boolean
): number => {
  const baseRate = colorMode === 'bw' ? 2.0 : 5.0;
  const qualityMultiplier = highQuality ? 1.5 : 1.0;
  return pages * copies * baseRate * qualityMultiplier;
};

